#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." > /dev/null && pwd)"
WRANGLER_JSONC="$REPO_ROOT/wrangler.jsonc"
WRANGLER_M2_JSONC="$REPO_ROOT/wrangler.m2.jsonc"

# write_var is shared with checkpoint-b-access-policy.sh — see _lib.sh.
# shellcheck source=ops/checkpoints/_lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"

# ENV_FILE is the vendored library's resume cache (ask() offers its values
# as defaults on re-run — "[Enter keeps current]"). Matches .gitignore's
# .dev.vars* pattern; holds non-secret IDs only (same trust level as the
# committed wrangler.jsonc placeholders they mirror), purely so re-running
# this wizard after an interruption doesn't mean retyping already-given
# values. Safe to delete once Checkpoint A is done.
ENV_FILE="$REPO_ROOT/.dev.vars.checkpoint-a"

# put_wrangler_secret NAME FILE — pipe a file's exact bytes into a Cloudflare
# Worker secret. Never echoed; never written to ENV_FILE or Git.
put_wrangler_secret() {
  local name="$1" file="$2"
  if ! command -v pnpm >/dev/null 2>&1; then
    SKIPPED+=("Worker secret $name — pnpm not on PATH; run: pnpm exec wrangler secret put $name < $file")
    warn "skipped Worker secret $name — pnpm not found"
    return
  fi
  if (cd "$REPO_ROOT" > /dev/null && pnpm exec wrangler secret put "$name" < "$file"); then
    WRITTEN_SECRET+=("$name (Cloudflare Worker secret)")
    printf '  %s✓ set%s Cloudflare Worker secret %s\n' "$GREEN" "$RESET" "$name"
  else
    SKIPPED+=("Worker secret $name — wrangler secret put failed; retry manually")
    warn "failed to set Worker secret $name"
  fi
}

banner "Checkpoint A — GitHub App + secrets"
say "Creates the Studio GitHub App, installs it on DarkoKuzmanovic/jelementi"
say "only, enables repo auto-merge + delete-merged-branches, and stores the"
say "resulting identifiers/secret. Nothing here is reversible without a"
say "separate action — see docs/agents/../runbooks/studio-operations.md."
warn "Run this on a dedicated branch (e.g. ops/studio-checkpoint-config), not"
warn "main — the wrangler.jsonc/wrangler.m2.jsonc writes below go through a"
warn "normal PR; Checkpoint C is that PR's protected merge."

# ── Stage 1: create the GitHub App ─────────────────────────────────────────
stage "Create the GitHub App"
say "One GitHub App, owned by DarkoKuzmanovic, used only by Jelementi Studio."
open_url "https://github.com/settings/apps/new"
step "GitHub App name: e.g. 'jelementi-studio' (must be globally unique)."
step "Homepage URL: https://jelementi.quz.ma"
step "Webhook: UNCHECK 'Active' — Studio always reads GitHub fresh, no webhook."
step "Repository permissions → Contents: Read and write."
step "Repository permissions → Pull requests: Read and write."
step "Repository permissions → Checks: Read-only."
step "Metadata permission stays Read-only (mandatory default) — leave it."
step "Where can this GitHub App be installed? → Only on this account."
step "Click 'Create GitHub App'."
pause "Created? Press Enter to continue."
step "On the app's General page, copy the App ID (numeric, top of page)."
ask GITHUB_APP_ID "Paste the App ID:"
step "On the same page, copy the Client ID."
ask GITHUB_APP_CLIENT_ID "Paste the Client ID:"
step "Scroll to 'Private keys' → 'Generate a private key' → a .pem downloads."
ask GITHUB_APP_PRIVATE_KEY_PATH "Full path to the downloaded .pem file:"
GITHUB_APP_PRIVATE_KEY_PATH="${GITHUB_APP_PRIVATE_KEY_PATH/#\~/$HOME}"
if [[ ! -f "$GITHUB_APP_PRIVATE_KEY_PATH" ]]; then
  warn "file not found at '$GITHUB_APP_PRIVATE_KEY_PATH' — paste the FULL absolute"
  warn "path (e.g. /home/you/Downloads/app.pem), then re-run this wizard."
  exit 1
fi
write_var GITHUB_APP_ID "$GITHUB_APP_ID"
write_var GITHUB_APP_CLIENT_ID "$GITHUB_APP_CLIENT_ID"
write_env GITHUB_APP_ID "$GITHUB_APP_ID"
write_env GITHUB_APP_CLIENT_ID "$GITHUB_APP_CLIENT_ID"
write_env GITHUB_APP_PRIVATE_KEY_PATH "$GITHUB_APP_PRIVATE_KEY_PATH"
note "(Non-secret — the real values live in wrangler.jsonc/wrangler.m2.jsonc;"
note " also cached in $ENV_FILE so a re-run offers them as defaults instead"
note " of asking you to retype them.)"

# ── Stage 2: install on this repo only ─────────────────────────────────────
stage "Install on DarkoKuzmanovic/jelementi only"
say "Installing grants the App the permissions from Stage 1 on one repo."
open_url "https://github.com/settings/apps"
step "Open the App you just created → 'Install App' in the left sidebar."
step "Choose 'Only select repositories' → select ONLY 'jelementi'. Confirm."
step "After install, the browser URL becomes .../settings/installations/<id>."
ask GITHUB_INSTALLATION_ID "Paste the numeric installation id from that URL:"
write_var GITHUB_INSTALLATION_ID "$GITHUB_INSTALLATION_ID"
write_env GITHUB_INSTALLATION_ID "$GITHUB_INSTALLATION_ID"

# ── Stage 3: repo auto-merge + delete-merged-branches ──────────────────────
stage "Repo settings — auto-merge + delete merged branches"
say "Publish relies on GitHub auto-merge; Discard/Publish rely on a clean"
say "branch namespace, so merged Studio branches should not linger."
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  CURRENT=$(gh api repos/DarkoKuzmanovic/jelementi --jq '{allow_auto_merge, delete_branch_on_merge}' 2>/dev/null || echo '{}')
  say "Current: $CURRENT"
  if confirm "Enable allow_auto_merge + delete_branch_on_merge now via gh api?"; then
    gh api -X PATCH repos/DarkoKuzmanovic/jelementi \
      -f allow_auto_merge=true -f delete_branch_on_merge=true >/dev/null
    VERIFY=$(gh api repos/DarkoKuzmanovic/jelementi --jq '{allow_auto_merge, delete_branch_on_merge}')
    printf '  %s✓ read back%s %s\n' "$GREEN" "$RESET" "$VERIFY"
  fi
else
  warn "gh not authenticated — enable manually:"
  step "Settings → General → Pull Requests → check 'Allow auto-merge'."
  step "Settings → General → Pull Requests → check 'Automatically delete head branches'."
fi
open_url "https://github.com/DarkoKuzmanovic/jelementi/settings"
step "Confirm both toggles are ON before continuing."
pause

# ── Stage 4: store the private key ─────────────────────────────────────────
stage "Store the private key"
say "The .pem is put straight into a Cloudflare Worker secret — its bytes"
say "are never echoed, written to $ENV_FILE, or committed."
if confirm "Set Cloudflare Worker secret GITHUB_APP_PRIVATE_KEY now (overwrites any existing value)?"; then
  put_wrangler_secret GITHUB_APP_PRIVATE_KEY "$GITHUB_APP_PRIVATE_KEY_PATH"
else
  SKIPPED+=("Worker secret GITHUB_APP_PRIVATE_KEY — declined; run: pnpm exec wrangler secret put GITHUB_APP_PRIVATE_KEY < $GITHUB_APP_PRIVATE_KEY_PATH")
fi
say "For local dev, also add it to .dev.vars (gitignored, never committed):"
note "  printf 'GITHUB_APP_PRIVATE_KEY=\"%s\"\n' \"\$(cat $GITHUB_APP_PRIVATE_KEY_PATH)\" >> .dev.vars"
if confirm "Append it to .dev.vars now?"; then
  {
    printf 'GITHUB_APP_PRIVATE_KEY="'
    cat "$GITHUB_APP_PRIVATE_KEY_PATH"
    printf '"\n'
  } >> "$REPO_ROOT/.dev.vars"
  printf '  %s✓ appended%s GITHUB_APP_PRIVATE_KEY to .dev.vars\n' "$GREEN" "$RESET"
fi
say "Delete the downloaded .pem from Downloads/ once both are set — it has"
say "no further use outside this wizard."

# ── Stage 5: credential-hygiene verification ────────────────────────────────
stage "Verify: App scope + no leaked credentials"
step "On the App's 'Install App' page, confirm exactly ONE repository is"
step "checked: jelementi. Confirm no other account/org shows an install."
say "Scanning tracked + untracked files, and any built bundle, for a leaked key…"
LEAK_SCAN=/tmp/jelementi-checkpoint-a-leak-scan
: > "$LEAK_SCAN"
if command -v git >/dev/null 2>&1; then
  (cd "$REPO_ROOT" > /dev/null && git grep -l 'BEGIN.*PRIVATE KEY' -- . ':!ops/checkpoints/*' 2>/dev/null) >>"$LEAK_SCAN"
  (cd "$REPO_ROOT" > /dev/null && git ls-files --others --exclude-standard -z | xargs -0 -r grep -l 'BEGIN.*PRIVATE KEY' 2>/dev/null) >>"$LEAK_SCAN"
fi
if [[ -d "$REPO_ROOT/.svelte-kit/output/client" ]]; then
  grep -rl 'BEGIN.*PRIVATE KEY' "$REPO_ROOT/.svelte-kit/output/client" 2>/dev/null >>"$LEAK_SCAN"
  if [[ -n "${GITHUB_APP_PRIVATE_KEY_PATH:-}" ]]; then
    warn "also grep the client bundle for the App ID/Client ID literal values yourself —"
    warn "they're short enough to false-positive on automatically, so this is manual."
  fi
else
  note "no client build present (.svelte-kit/output/client) — nothing to scan there yet;"
  note "re-run this check after 'pnpm build' or before Checkpoint C's deploy."
fi
if [[ -s "$LEAK_SCAN" ]]; then
  warn "POSSIBLE LEAK — matches in:"
  cat "$LEAK_SCAN"
  SKIPPED+=("credential-leak scan found matches — see $LEAK_SCAN")
else
  printf '  %s✓%s no private-key pattern found in tracked, untracked, or built-client files\n' "$GREEN" "$RESET"
fi
if (cd "$REPO_ROOT" > /dev/null && git check-ignore -q .dev.vars 2>/dev/null); then
  printf '  %s✓%s .dev.vars is gitignored\n' "$GREEN" "$RESET"
else
  warn ".dev.vars is NOT gitignored — fix before continuing"
  SKIPPED+=(".dev.vars is not gitignored")
fi
say "Also confirm manually: no App ID/Client ID/Installation ID/private key"
say "value appears in this terminal's scrollback once you close it, and"
say "none reached a browser bundle (Studio server modules are never bundled"
say "into client output — see ADR CONTEXT.md 'GitHub adapter' seam)."

finish
note "Next: docs/runbooks/studio-operations.md, then Checkpoint B
  (ops/checkpoints/checkpoint-b-access-policy.sh)."
