#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." > /dev/null && pwd)"
WRANGLER_JSONC="$REPO_ROOT/wrangler.jsonc"
WRANGLER_M2_JSONC="$REPO_ROOT/wrangler.m2.jsonc"

# write_var is shared with checkpoint-a-github-app.sh — see _lib.sh.
# shellcheck source=ops/checkpoints/_lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/_lib.sh"

# ENV_FILE is the vendored library's resume cache (ask() offers its values
# as defaults on re-run — "[Enter keeps current]"). Matches .gitignore's
# .dev.vars* pattern; holds non-secret IDs only (same trust level as the
# committed wrangler.jsonc placeholders they mirror). Safe to delete once
# Checkpoint B is done.
ENV_FILE="$REPO_ROOT/.dev.vars.checkpoint-b"

banner "Checkpoint B — Cloudflare Access Studio policy"
say "Creates the Access application protecting /studio* in production,"
say "scoped to exactly one operator email, and stores the resulting AUD/"
say "team-domain/email identifiers. See docs/runbooks/studio-operations.md"
say "for the app-level auth boundary this policy sits in front of."
warn "Until this checkpoint completes, /studio is reachable anonymously at"
warn "the Cloudflare edge (it currently fails closed app-side on missing"
warn "config, but nothing blocks the request from reaching the Worker)."
warn "Run this on the SAME dedicated branch as Checkpoint A (e.g."
warn "ops/studio-checkpoint-config) so both var writes land in one PR."

# ── Stage 1: confirm the Zero Trust team ──────────────────────────────
stage "Confirm the Zero Trust team"
say "M2 already created the 'Cloudflare Workers Preview URLs' Access policy"
say "under one Zero Trust team. Reuse that same team — do not create a new one."
open_url "https://one.dash.cloudflare.com"
step "Confirm the team name in the top-left (M2 recorded 'quzma')."
ask ACCESS_TEAM_NAME "Team name only, no https:// and no domain suffix (e.g. 'quzma'):"
write_env ACCESS_TEAM_NAME "$ACCESS_TEAM_NAME"
ACCESS_TEAM_DOMAIN="https://${ACCESS_TEAM_NAME}.cloudflareaccess.com"
write_env ACCESS_TEAM_DOMAIN "$ACCESS_TEAM_DOMAIN"
printf '  %s✓%s ACCESS_TEAM_DOMAIN will be %s\n' "$GREEN" "$RESET" "$ACCESS_TEAM_DOMAIN"

# ── Stage 2: create the Studio Access application ──────────────────────────
stage "Create the Studio Access application"
# NOTE: <team>.cloudflareaccess.com is the Access *authentication* domain
# (login challenges, JWKS) — it is never the admin dashboard UI, so it
# cannot be used to build a dashboard deep link. Cloudflare's dashboard nav
# has also moved since the M2 runbook was written (rebranded "Cloudflare
# One", apps now live under Access controls → Applications), so this opens
# the dashboard root and gives manual navigation instead of a guessed URL.
open_url "https://one.dash.cloudflare.com"
step "Left nav → Access controls → Applications (was 'Access → Applications'"
step "  before the Cloudflare One rebrand — same page, different label)."
step "Add an application → 'Self-hosted and private'."
step "Destination type: 'Public DNS' (jelementi.quz.ma is a custom-domain"
step "  Worker route, not a *.workers.dev address)."
step "Destinations → Public hostnames → Subdomain: 'jelementi', Domain:"
step "  'quz.ma' (pick it from the zone dropdown — jelementi.quz.ma is a"
step "  subdomain of the quz.ma zone, it will not appear as its own entry),"
step "  Path: 'studio*' (no leading slash — Cloudflare adds it)."
note "  Every Studio server module lives under apps/web/src/routes/studio/;"
note "  there is no separate /api/studio surface as of this ticket. Re-run"
note "  'find apps/web/src/routes -path \"*studio*\"' before trusting that if"
note "  routes have changed since, and widen the path rule if so."
step "Application name: 'Jelementi Studio'."
step "Session duration: pick a short-to-medium duration (e.g. 24h) — this"
step "  is a single-operator publishing surface, not a public app."
step "You can add the Allow policy inline here, or in Stage 3 below — either"
step "  works; Stage 3 assumes you save the app first, then add the policy."
step "Save the application."

# ── Stage 3: the Allow policy ──────────────────────────────────────────────
stage "Add the operator-only Allow policy"
step "On the new application → Policies → Add a policy."
step "Policy name: 'Studio operator'. Action: Allow."
step "Include → Emails → enter the exact operator email (one address only)."
step "Do NOT add an Email domain, IP, or 'Everyone' rule — exact email only"
step "  (CONTEXT.md: 'Studio operator' is identified by one configured email)."
ask ALLOWED_OPERATOR_EMAIL "Operator email (this becomes a committed, non-secret wrangler var — same trust level as the existing placeholder):"
write_env ALLOWED_OPERATOR_EMAIL "$ALLOWED_OPERATOR_EMAIL"
step "Save the policy."

# ── Stage 4: capture the AUD tag and write vars ───────────────────────────
stage "Capture the AUD tag"
step "Open the application's Overview tab."
step "Copy the 'Application Audience (AUD) Tag' value."
ask ACCESS_AUD "Paste the AUD tag:"
write_env ACCESS_AUD "$ACCESS_AUD"
write_var ACCESS_TEAM_DOMAIN "$ACCESS_TEAM_DOMAIN"
write_var ACCESS_AUD "$ACCESS_AUD"
write_var ALLOWED_OPERATOR_EMAIL "$ALLOWED_OPERATOR_EMAIL"
note "(Non-secret — the real values live in wrangler.jsonc/wrangler.m2.jsonc;"
note " also cached in $ENV_FILE so a re-run offers them as defaults instead"
note " of asking you to retype them.)"

# ── Stage 5: verify the edge actually enforces this ─────────────────────────
stage "Verify enforcement"
say "These checks run against Cloudflare's own Access challenge, in front of"
say "whatever the Worker currently serves — they do not require Checkpoint C."
say "A failure here is a hard stop: this checkpoint is not done until every"
say "check below passes for real, not just recorded and skipped past."
step "In a private/incognito window (no Cloudflare Access session), open:"
open_url "https://jelementi.quz.ma/studio"
if ! confirm "Did the incognito window get an Access login challenge (NOT the Studio page)?"; then
  warn "anonymous access was NOT challenged — Access is misconfigured"
  warn "STOP — fix the application/policy above, then re-run this wizard."
  SKIPPED+=("anonymous /studio request was not challenged by Access")
  exit 1
fi
step "In your normal, authenticated browser, open the same URL and log in"
step "  with Cloudflare Access using the exact operator email from Stage 3."
if ! confirm "Did the operator identity get past the Access challenge?"; then
  warn "operator was blocked — re-check the policy email in Stage 3"
  warn "STOP — fix the policy above, then re-run this wizard."
  SKIPPED+=("operator identity did not pass the Access policy")
  exit 1
fi
say "Wrong-identity denial: the Allow policy in Stage 3 is a single exact-"
say "email rule with no domain/IP/Everyone fallback, so Access denies any"
say "other authenticated identity by construction — there is no separate"
say "toggle to misconfigure. If a second real identity (a different Google/"
say "GitHub/email login you control) is available, confirm it directly:"
if confirm "Do you have a second identity available to test right now?"; then
  step "Log out of the operator identity, then log in as the second identity"
  step "  at the same URL."
  if ! confirm "Was the second identity denied by the Access policy?"; then
    warn "a non-operator identity reached Studio — Access is misconfigured"
    warn "STOP — fix the policy above, then re-run this wizard."
    SKIPPED+=("a non-operator identity was not denied by Access")
    exit 1
  fi
else
  note "skipped the live second-identity check — relying on the exact-email"
  note "Allow-rule construction argument above; note this in Checkpoint C's"
  note "'anonymous/wrong-identity re-verified' evidence."
fi
say "App-level rejection of a bad assertion (wrong issuer/audience/email/"
say "expired token) is covered by apps/web/src/lib/server/studio/"
say "access-auth.server.ts's existing test suite (pnpm test) — re-run it now"
say "as evidence that the app-level check still fails closed:"
note "  pnpm --filter @jelementi/web test -- access-auth"
if command -v pnpm >/dev/null 2>&1; then
  if ! (cd "$REPO_ROOT" > /dev/null && pnpm --filter @jelementi/web test -- access-auth); then
    warn "access-auth test suite failed — STOP, do not proceed to Checkpoint C"
    exit 1
  fi
else
  warn "pnpm not on PATH — run the access-auth test suite manually before proceeding"
  SKIPPED+=("access-auth test suite not run — pnpm not found")
fi

finish
note "Next: re-verify with docs/runbooks/studio-checkpoints-c-d.md before
  requesting Checkpoint C approval."
