<script lang="ts">
  import type { StudioEditorData, StudioPreviewInput } from '$lib/server/studio/editor.server';
  import type { StudioPreviewResult } from '$lib/studio/contracts';
  import ArticleRenderer from '$lib/article/ArticleRenderer.svelte';

  let {
    editor,
    submitted,
    preview,
  }: {
    editor: StudioEditorData;
    submitted?: StudioPreviewInput;
    preview?: StudioPreviewResult;
  } = $props();

  const visible = $derived(submitted ?? { metadata: editor.metadata, body: editor.body });
  const metadata = $derived(visible.metadata);
</script>

<section aria-labelledby="studio-editor-heading">
  <p class="eyebrow">{metadata.status === 'draft' ? 'Draft article' : 'Canonical article'}</p>
  <h2 id="studio-editor-heading">{metadata.title}</h2>
  <p>Preview is compiled on the server from the current form. No draft is saved automatically.</p>

  <form method="POST" action="?/preview" class="studio-editor-form">
    <fieldset>
      <legend>Article metadata</legend>
      <label>
        Title
        <input name="title" value={metadata.title} required />
      </label>
      <label>
        Slug
        <input name="slug" value={metadata.slug} readonly={!editor.slugEditable} required />
      </label>
      <label>
        Excerpt
        <textarea name="excerpt" rows="3" required>{metadata.excerpt}</textarea>
      </label>
      <label>
        Updated date
        <input name="updatedAt" value={metadata.updatedAt} required />
      </label>
      <label>
        Published date
        <input name="publishedAt" value={metadata.publishedAt ?? ''} />
      </label>
      <label>
        Status
        <select name="status" value={metadata.status}>
          <option value="draft">Draft</option>
          <option value="published">Published</option>
          <option value="archived">Archived</option>
        </select>
      </label>
      <label>
        Category
        <input name="category" value={metadata.category} required />
      </label>
      <label>
        Tags <span>(comma-separated)</span>
        <input name="tags" value={metadata.tags.join(', ')} />
      </label>
      <label>
        Author
        <input name="author" value={metadata.author} required />
      </label>
    </fieldset>

    <fieldset>
      <legend>Cover</legend>
      <label>
        Media key
        <input name="coverSrc" value={metadata.cover.src} required />
      </label>
      <label>
        Alt text
        <input name="coverAlt" value={metadata.cover.alt} />
      </label>
    </fieldset>

    <fieldset>
      <legend>Audio (optional)</legend>
      <label>
        Media key
        <input name="audioSrc" value={metadata.audio?.src ?? ''} />
      </label>
      <label>
        Duration in seconds
        <input
          name="audioDurationSeconds"
          type="number"
          min="1"
          value={metadata.audio?.durationSeconds ?? ''}
        />
      </label>
    </fieldset>

    <fieldset>
      <legend>References</legend>
      {#each metadata.references as reference, index (index)}
        <div class="studio-reference-fields">
          <label>
            Title
            <input name="referenceTitle" value={reference.title} />
          </label>
          <label>
            URL
            <input name="referenceUrl" type="url" value={reference.url} />
          </label>
          <label>
            Publisher
            <input name="referencePublisher" value={reference.publisher ?? ''} />
          </label>
          <label>
            Accessed date
            <input name="referenceAccessedAt" value={reference.accessedAt ?? ''} />
          </label>
        </div>
      {/each}
      <div class="studio-reference-fields" aria-label="New reference">
        <label>
          Title
          <input name="referenceTitle" />
        </label>
        <label>
          URL
          <input name="referenceUrl" type="url" />
        </label>
        <label>
          Publisher
          <input name="referencePublisher" />
        </label>
        <label>
          Accessed date
          <input name="referenceAccessedAt" />
        </label>
      </div>
    </fieldset>

    <fieldset>
      <legend>Markdown body</legend>
      <label>
        Body
        <textarea name="body" rows="18">{visible.body}</textarea>
      </label>
      <p>Reading time is generated by the compiler and is not editable.</p>
    </fieldset>

    <input type="hidden" name="baseMainSha" value={editor.concurrency.baseMainSha} />
    {#if editor.concurrency.draftHeadSha}
      <input type="hidden" name="draftHeadSha" value={editor.concurrency.draftHeadSha} />
    {/if}
    {#if editor.concurrency.expectedBlobSha}
      <input type="hidden" name="expectedBlobSha" value={editor.concurrency.expectedBlobSha} />
    {/if}
    <button type="submit">Preview</button>
  </form>

  {#if preview?.kind === 'preview_issues'}
    <section aria-labelledby="preview-issues-heading">
      <h3 id="preview-issues-heading">Preview needs attention</h3>
      <ul>
        {#each preview.compileIssues as issue, index (index)}
          <li>
            {issue.code}: {issue.message} ({issue.sourcePath}:{issue.line ?? 1}:{issue.column ?? 1})
          </li>
        {/each}
      </ul>
    </section>
  {:else if preview?.kind === 'preview_ok'}
    <section aria-labelledby="preview-heading">
      <h3 id="preview-heading">Preview</h3>
      <ArticleRenderer document={preview.document} />
    </section>
  {/if}
</section>
