/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 753ed2796095bf90207d2a69155aa4d1)
interface __BaseEnv_Env {
	R2_MEDIA: R2Bucket;
	ASSETS: Fetcher;
	ACCESS_AUD: "change-me-at-checkpoint-b";
	ACCESS_TEAM_DOMAIN: "https://change-me-at-checkpoint-b.cloudflareaccess.com";
	ALLOWED_OPERATOR_EMAIL: "change-me-at-checkpoint-b";
	GITHUB_APP_CLIENT_ID: "change-me-at-checkpoint-a";
	GITHUB_APP_ID: "change-me-at-checkpoint-a";
	GITHUB_INSTALLATION_ID: "change-me-at-checkpoint-a";
	GITHUB_REPO_NAME: "jelementi";
	GITHUB_REPO_OWNER: "DarkoKuzmanovic";
	PRODUCTION_ORIGIN: "https://jelementi.quz.ma";
	PUBLIC_MEDIA_BASE_URL: "https://media.jelementi.quz.ma/";
	GITHUB_APP_PRIVATE_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.svelte-kit/cloudflare/_worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
