/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 6aa2fb875e8c51ed1066a012678e3105)
interface __BaseEnv_Env {
  R2_MEDIA: R2Bucket;
  ASSETS: Fetcher;
  ACCESS_AUD: 'b8ab323d9d804dd26a17dafe9abbdd519e93d146cb0a7aabbdbe002b7d221735';
  ACCESS_TEAM_DOMAIN: 'https://quzma.cloudflareaccess.com';
  ALLOWED_OPERATOR_EMAIL: 'darko.kuzmanovic@gmail.com';
  GITHUB_APP_CLIENT_ID: 'Iv23lijel88VeotOZ5at';
  GITHUB_APP_ID: '4617065';
  GITHUB_INSTALLATION_ID: '154254277';
  GITHUB_REPO_NAME: 'jelementi';
  GITHUB_REPO_OWNER: 'DarkoKuzmanovic';
  PRODUCTION_ORIGIN: 'https://jelementi.quz.ma';
  PUBLIC_MEDIA_BASE_URL: 'https://media.jelementi.quz.ma/';
  GITHUB_APP_PRIVATE_KEY: string;
  SELF: Service<typeof import('./.svelte-kit/cloudflare/_worker').default>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./.svelte-kit/cloudflare/_worker');
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'ACCESS_AUD'
      | 'ACCESS_TEAM_DOMAIN'
      | 'ALLOWED_OPERATOR_EMAIL'
      | 'GITHUB_APP_CLIENT_ID'
      | 'GITHUB_APP_ID'
      | 'GITHUB_INSTALLATION_ID'
      | 'GITHUB_REPO_NAME'
      | 'GITHUB_REPO_OWNER'
      | 'PRODUCTION_ORIGIN'
      | 'PUBLIC_MEDIA_BASE_URL'
      | 'GITHUB_APP_PRIVATE_KEY'
    >
  > {}
}
