/* eslint-disable @typescript-eslint/triple-slash-reference */
/// <reference path="../../worker-configuration.d.ts" />

declare global {
  type WorkerEnv = Cloudflare.Env;

  namespace App {
    // Cloudflare bindings are generated by `wrangler types` into
    // `worker-configuration.d.ts` (see the `secrets`/`vars` sections of
    // `wrangler.jsonc` and `wrangler.m2.jsonc`); `Cloudflare.Env` is the
    // binding bag exposed on the server as `event.platform.env`.
    interface Platform {
      env?: WorkerEnv;
    }
  }
}

export {};
