/**
 * Studio runtime configuration.
 *
 * The runtime binding bag is declared in `wrangler.jsonc` and
 * `wrangler.m2.jsonc` (non-secret identifiers as `vars`, credentials as
 * `secrets.required`) and its TypeScript shape is generated by `wrangler
 * types` into `worker-configuration.d.ts` — this module never hand-writes an
 * `Env` type. Missing or malformed configuration fails closed with a
 * sanitized `StudioConfigError` that names only binding identifiers, never
 * values.
 */

/** Non-secret identifiers declared as `vars` in both Wrangler contracts. */
export const STUDIO_VAR_BINDINGS = [
  'ACCESS_AUD',
  'ACCESS_TEAM_DOMAIN',
  'ALLOWED_OPERATOR_EMAIL',
  'GITHUB_APP_CLIENT_ID',
  'GITHUB_APP_ID',
  'GITHUB_INSTALLATION_ID',
  'GITHUB_REPO_NAME',
  'GITHUB_REPO_OWNER',
  'PRODUCTION_ORIGIN',
  'PUBLIC_MEDIA_BASE_URL',
] as const;

/** Credentials declared as required secrets in both Wrangler contracts. */
export const STUDIO_SECRET_BINDINGS = ['GITHUB_APP_PRIVATE_KEY'] as const;

export interface StudioAccessConfig {
  teamDomain: string;
  audience: string;
  allowedEmail: string;
}

export interface StudioGithubConfig {
  appId: string;
  clientId: string;
  installationId: string;
  owner: string;
  repo: string;
  privateKey: string;
}

export interface StudioConfig {
  access: StudioAccessConfig;
  github: StudioGithubConfig;
  productionOrigin: string;
  mediaBaseUrl: string;
}

export class StudioConfigError extends Error {
  readonly missingBindings: readonly string[];

  constructor(missingBindings: readonly string[]) {
    super(`Studio configuration is incomplete: ${missingBindings.join(', ')}.`);
    this.name = 'StudioConfigError';
    this.missingBindings = missingBindings;
  }
}

const HTTPS_PROTOCOL = /^https:$/i;
const HTTP_PROTOCOL = /^https?:$/i;
const EMAIL_PATTERN = /^[^@\s]+@[^@\s]+$/;
const NUMERIC_PATTERN = /^[0-9]+$/;
const PEM_MARKER = '-----BEGIN';

function isValidUrl(value: string, protocol: RegExp): boolean {
  try {
    const parsed = new URL(value);
    return protocol.test(parsed.protocol) && parsed.hostname.length > 0;
  } catch {
    return false;
  }
}

/** One documented normalization rule: trim ASCII whitespace, then lowercase. */
export function normalizeEmail(value: string): string {
  return value.trim().toLowerCase();
}

function readString(env: WorkerEnv | undefined, key: string): string | undefined {
  const value = (env as Readonly<Record<string, unknown>> | undefined)?.[key];
  if (typeof value !== 'string') return undefined;
  const trimmed = value.trim();
  return trimmed.length === 0 ? undefined : trimmed;
}

/**
 * Validates every Studio/GitHub binding and returns the typed configuration.
 * Any missing, empty, or malformed binding fails closed and every offending
 * binding name is reported in sorted order.
 */
export function getStudioConfig(env: WorkerEnv | undefined): StudioConfig {
  const missing: string[] = [];
  const report = (key: string): void => {
    missing.push(key);
  };

  const teamDomain = readString(env, 'ACCESS_TEAM_DOMAIN');
  if (teamDomain === undefined || !isValidUrl(teamDomain, HTTPS_PROTOCOL)) {
    report('ACCESS_TEAM_DOMAIN');
  }

  const audience = readString(env, 'ACCESS_AUD');
  if (audience === undefined) report('ACCESS_AUD');

  const allowedEmail = readString(env, 'ALLOWED_OPERATOR_EMAIL');
  if (allowedEmail === undefined || !EMAIL_PATTERN.test(allowedEmail)) {
    report('ALLOWED_OPERATOR_EMAIL');
  }

  const appId = readString(env, 'GITHUB_APP_ID');
  if (appId === undefined) report('GITHUB_APP_ID');

  const clientId = readString(env, 'GITHUB_APP_CLIENT_ID');
  if (clientId === undefined) report('GITHUB_APP_CLIENT_ID');

  const installationId = readString(env, 'GITHUB_INSTALLATION_ID');
  if (installationId === undefined || !NUMERIC_PATTERN.test(installationId)) {
    report('GITHUB_INSTALLATION_ID');
  }

  const owner = readString(env, 'GITHUB_REPO_OWNER');
  if (owner === undefined) report('GITHUB_REPO_OWNER');

  const repo = readString(env, 'GITHUB_REPO_NAME');
  if (repo === undefined) report('GITHUB_REPO_NAME');

  const privateKey = readString(env, 'GITHUB_APP_PRIVATE_KEY');
  if (privateKey === undefined || !privateKey.startsWith(PEM_MARKER)) {
    report('GITHUB_APP_PRIVATE_KEY');
  }

  const productionOrigin = readString(env, 'PRODUCTION_ORIGIN');
  if (productionOrigin === undefined || !isValidUrl(productionOrigin, HTTPS_PROTOCOL)) {
    report('PRODUCTION_ORIGIN');
  }

  const mediaBaseUrl = readString(env, 'PUBLIC_MEDIA_BASE_URL');
  if (mediaBaseUrl === undefined || !isValidUrl(mediaBaseUrl, HTTP_PROTOCOL)) {
    report('PUBLIC_MEDIA_BASE_URL');
  }

  if (missing.length > 0) {
    throw new StudioConfigError([...new Set(missing)].sort());
  }

  return {
    access: {
      teamDomain: teamDomain as string,
      audience: audience as string,
      allowedEmail: normalizeEmail(allowedEmail as string),
    },
    github: {
      appId: appId as string,
      clientId: clientId as string,
      installationId: installationId as string,
      owner: owner as string,
      repo: repo as string,
      privateKey: privateKey as string,
    },
    productionOrigin: productionOrigin as string,
    mediaBaseUrl: mediaBaseUrl as string,
  };
}
