import type { GeneratedContent } from './generated-content';

export interface PodcastFeedOptions {
  siteOrigin: string;
  byteLengths: Readonly<Record<string, number>>;
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

const audioMimeByExtension: Record<string, string> = { mp3: 'audio/mpeg', m4a: 'audio/mp4' };

function audioMimeType(src: string): string {
  // ponytail: pathname only — a query string must not change the MIME type.
  const extension = new URL(src).pathname.split('.').at(-1)?.toLowerCase() ?? '';
  return audioMimeByExtension[extension] ?? 'audio/mpeg';
}

function rssDate(publishedAt: string): string {
  const normalized = publishedAt.length === 10 ? `${publishedAt}T00:00:00Z` : publishedAt;
  return new Date(normalized).toUTCString();
}

/**
 * Pure RSS 2.0 + iTunes feed over the validated published catalog. Articles
 * without audio are skipped; published audio without a generated byte length
 * throws — a silent omission would desync subscribers. The episode GUID is
 * the article URL (identity), so replacing the audio file never creates a
 * new episode. Item order follows the validated index (newest-first).
 */
export function buildPodcastFeed(content: GeneratedContent, options: PodcastFeedOptions): string {
  const origin = options.siteOrigin.replace(/\/$/, '');
  const feedUrl = `${origin}/podcast.xml`;
  const items: string[] = [];
  for (const indexEntry of content.index) {
    const article = content.articles[indexEntry.slug];
    const src = article?.audio?.src;
    if (article === undefined || src === undefined) continue;
    const length = options.byteLengths[src];
    if (length === undefined) {
      throw new Error(
        `Podcast feed is missing a generated byte length for article "${article.slug}" audio: ${src}.`,
      );
    }
    const url = `${origin}/articles/${article.slug}`;
    const type = audioMimeType(src);
    const duration =
      article.audio?.durationSeconds === undefined
        ? ''
        : `      <itunes:duration>${article.audio.durationSeconds}</itunes:duration>\n`;
    items.push(
      [
        '    <item>',
        `      <title>${escapeXml(article.title)}</title>`,
        `      <description>${escapeXml(article.excerpt)}</description>`,
        `      <link>${escapeXml(url)}</link>`,
        `      <guid isPermaLink="true">${escapeXml(url)}</guid>`,
        `      <pubDate>${rssDate(indexEntry.publishedAt)}</pubDate>`,
        `      <enclosure url="${escapeXml(src)}" length="${length}" type="${type}" />`,
        `${duration}    </item>`,
      ].join('\n'),
    );
  }
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<rss version="2.0" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xmlns:atom="http://www.w3.org/2005/Atom">',
    '  <channel>',
    '    <title>Jelementi</title>',
    `    <link>${escapeXml(origin)}</link>`,
    '    <description>Curious, careful stories from nearby and far away — the Jelementi audio feed.</description>',
    '    <language>en</language>',
    `    <atom:link href="${escapeXml(feedUrl)}" rel="self" type="application/rss+xml" />`,
    '    <itunes:author>Jelementi</itunes:author>',
    items.join('\n'),
    '  </channel>',
    '</rss>',
    '',
  ].join('\n');
}
